name: gofact
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.18.0
  cloud_firestore: ^3.1.18
  provider: ^6.0.3
  path_provider: ^2.0.11
  sqflite: ^2.0.2+1
  splashscreen: ^1.3.5
  webview_flutter: ^3.0.4
  pdf: ^3.8.1
  printing: ^5.9.1
  open_file: ^3.1.0
  firebase_storage: ^10.3.1
  flutter_downloader: ^1.4.4
  dio: ^4.0.0
  url_launcher: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/Gofact.png"

flutter:
  assets:
    - assets/
    - assets/fondo.jpg
  uses-material-design: true
